import mock from '../mock'

const employees = [
  {
    id: 1,
    name: 'Javier Andrés',
    lastname: 'Soto Pereira',
    phone: '+569 44650909',
    email: 'jsoto@asiph.cl',
    job: 'Frontend Developer',
    address: 'Avda. España 1234',
    date_start: '01/09/2010',
    status: true,
  },
  {
    id: 2,
    name: 'Andrés',
    lastname: 'Maldonado Ramírez',
    phone: '+569 95651900',
    email: 'amaldonado@asiph.cl',
    job: 'Frontend Developer',
    address: 'Arauco 327',
    date_start: '01/09/2010',
    status: true,
  },
  {
    id: 3,
    name: 'Yerco ignacio',
    lastname: 'Moreira Cuevas',
    phone: '+569 83331922',
    email: 'ymoreira@asiph.cl',
    job: 'Backend Developer',
    address: 'Orompello 129',
    date_start: '01/09/2010',
    status: true,
  },
  {
    id: 4,
    name: 'Carlos Gabriel',
    lastname: 'Rios Sandoval',
    phone: '+569 44337699',
    email: 'crios@asiph.cl',
    job: 'Backend Developer',
    address: 'Chacabuco 768',
    date_start: '01/09/2010',
    status: true,
  },
  {
    id: 5,
    name: 'Pedro Pablo',
    lastname: 'Gonzalez Jara',
    phone: '+569 771595834',
    email: 'pgonzalez@asiph.cl',
    job: 'Software Architect',
    address: 'Isabel Rodas 247',
    date_start: '01/09/2010',
    status: true,
  },
]

mock.onGet('/api/v1/employees').reply(() => [200, employees])
