export const rules = {
  superadministrator: [
    'dashboard:superadmin',
    'enterprises:edit',
    'enterprises:delete',
  ],
  administrator: [
    'dashboard:admin',
    'dashboard:manager',
    'areas:edit',
    'areas:delete',
    'workstations:add',
    'workstations:edit',
    'workstations:delete',
    'employees:add',
    'employees:edit',
    'employees:delete',
    'activities:add',
    'activities:edit',
    'activities:delete',
    'trainings:edit',
    'trainings:delete',
    'programs:add',
    'programs:edit',
    'programs:delete',
    'actions:edit',
    'actions:delete',
    'controls:add',
    'controls:edit',
    'controls:delete',
  ],
  chief_of_area: [
    'dashboard:manager',
    'dashboard:chief_of_area',
    'trainings:edit',
    'trainings:delete',
    'programs:edit',
    'programs:delete',
    'controls:add',
    'controls:edit',
    'controls:delete',
  ],
}
