export const headers = [
  {
    selector: 'activity_name',
    name: 'Actividad',
    sortable: true,
    minWidth: '200px',
    orderKey: 'activity.name',
  },
  {
    selector: 'accident',
    name: 'Accidente',
    sortable: true,
    center: true,
    minWidth: '100px',
  },
  {
    selector: '_risk_supervision_',
    name: 'Evaluación de riesgo',
    sortable: true,
    orderKey: 'risk',
    maxWidth: '100px',
  },
  {
    selector: 'worker_name',
    name: 'Trabajador',
    sortable: true,
    center: true,
    minWidth: '200px',
    orderKey: 'user.name',
  },
  {
    selector: 'workstation',
    name: 'Puesto de trabajo',
    sortable: true,
    minWidth: '150px',
    orderKey: 'activity.workstation',
  },
  {
    selector: 'area',
    name: 'Area',
    sortable: true,
    minWidth: '150px',
    orderKey: 'activity.area',
  },
  {
    selector: '_supervision_actions_',
    name: 'Acciones',
    sortable: true,
    center: true,
    maxWidth: '50px',
  },
]
