export const headers = [
  {
    // id: 'name',
    // title: 'Nombre',
    name: 'Nombre',
    selector: 'name',
    sortable: true,
  },
  {
    // id: 'total_activities',
    // title: 'Total actividades',
    name: 'Total actividades',
    selector: 'total_activities',
    maxWidth: '150px',
    sortable: true,
  },
  {
    // id: 'total_trainings',
    // title: 'Total capacitaciones',
    name: 'Total capacitaciones',
    selector: 'total_trainings',
    maxWidth: '150px',
    sortable: true,
  },
  {
    // id: 'total_programs',
    // title: 'Total programas',
    name: 'Total programas',
    selector: 'total_programs',
    maxWidth: '150px',
    sortable: true,
  },
  {
    // id: 'total_programs',
    // title: 'Total programas',
    name: '',
    selector: 'actions',
    maxWidth: '100px',
  },
]
