export const config = [
  [
    {
      input: 'CustomInput',
      key: 1,
      name: 'name',
      title: 'Nombres*',
      type: 'text',
      grid: 6,
    },
    {
      input: 'CustomInput',
      key: 2,
      name: 'lastname',
      title: 'Apellidos*',
      type: 'text',
      grid: 6,
    },
  ],
  [
    {
      input: 'CustomInput',
      key: 3,
      name: 'rut',
      title: 'RUT*',
      type: 'text',
      grid: 6,
    },
    {
      input: 'CustomInput',
      key: 4,
      name: 'email',
      title: 'Correo electrónico*',
      type: 'email',
      grid: 6,
    },
  ],
  [
    {
      input: 'CustomInput',
      key: 5,
      name: 'address',
      title: 'Dirección*',
      type: 'text',
      grid: 6,
    },
    {
      input: 'CustomInputAddon',
      key: 6,
      name: 'phone',
      title: 'Teléfono de contacto*',
      type: 'phone',
      prepend: '+56',
      grid: 6,
    },
  ],
  [
    {
      input: 'CustomSelect',
      key: 7,
      name: 'workstation_id',
      title: 'Puesto de trabajo*',
      type: 'text',
      options: [],
      grid: 6,
    },
    {
      input: 'CustomDatePicker',
      key: 8,
      name: 'date_start',
      title: 'Fecha de inicio laboral*',
      grid: 6,
    },
  ],
]
